name: Build and Release EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pygame

    - name: Build EXE
      run: |
        pyinstaller --noconsole music.py

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: music-player-exe
        path: dist/music.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: dist/music.exe
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}